version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - '5000:5000'
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - '3000:80'
    restart: unless-stopped
    depends_on:
      - server
